### ISSUE TITLE
Converter appears to be unhappy with some file uploads

### ISSUE THREAD

**Issue by morrowc** [routeviews/google-cloud-storage#17]
Error message from cloudrun console/logs: 

2022/01/18 19:55:42 http: panic serving 169.254.8.129:58343: runtime error: index out of range [5] with length 4
goroutine 77 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xaaeae0, 0xc00a0f2828})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/osrg/gobgp/pkg/packet/bgp.(*IPAddrPrefixDefault).decodePrefix(0xc009de3f80, {0xc003ed83f5, 0x0, 0x12}, 0x2a, 0xb3)
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/bgp/bgp.go:1178 +0x189
github.com/osrg/gobgp/pkg/packet/bgp.(*IPAddrPrefix).DecodeFromBytes(0xc009de3f80, {0xc003ed83f4, 0x13, 0x13}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/bgp/bgp.go:1230 +0x134
github.com/osrg/gobgp/pkg/packet/bgp.(*BGPUpdate).DecodeFromBytes(0xc00a384e40, {0xc003ed836b, 0x203002, 0x203002}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/bgp/bgp.go:9118 +0xcad
github.com/osrg/gobgp/pkg/packet/bgp.parseBody(0xc00047cf20, {0xc003ed836b, 0x98, 0x9c}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/bgp/bgp.go:9382 +0x278
github.com/osrg/gobgp/pkg/packet/bgp.ParseBGPMessage({0xc003ed8358, 0xc003ed8344, 0x40ee07}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/bgp/bgp.go:9397 +0xfc
github.com/osrg/gobgp/pkg/packet/mrt.(*BGP4MPMessage).DecodeFromBytes(0xc009de3e00, {0xc003ed8344, 0xc00047cfb8, 0x979a86})
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/mrt/mrt.go:810 +0x45
github.com/osrg/gobgp/pkg/packet/mrt.ParseMRTBody(0xc00047d13c, {0xc003ed8344, 0xc00047d030, 0xc3})
	/go/pkg/mod/github.com/osrg/gobgp@v2.0.0+incompatible/pkg/packet/mrt/mrt.go:1001 +0x612
github.com/routeviews/google-cloud-storage/pkg/mrt_converter.parseUpdate({0xc0056d5721, 0x10}, 0xc00047d13c, {0xc003ed8340, 0xc7, 0xc7})
	/app/pkg/mrt_converter/mrt_converter.go:159 +0x111
github.com/routeviews/google-cloud-storage/pkg/mrt_converter.convert({0xc0056d5721, 0x10}, {0xc01522a000, 0x1d00bb, 0x244000}, {0xbc2660, 0xc0022ce930}, 0xb27d28)
	/app/pkg/mrt_converter/mrt_converter.go:213 +0x469
github.com/routeviews/google-cloud-storage/pkg/mrt_converter.processMRTArchive({0xbd5bf8, 0xc000446a80}, 0xc000346140, 0xc00047d648, 0xc000314f00)
	/app/pkg/mrt_converter/mrt_converter.go:270 +0x24c
github.com/routeviews/google-cloud-storage/pkg/mrt_converter.ProcessMRTArchive(...)
	/app/pkg/mrt_converter/mrt_converter.go:249
main.(*server).archiveUploadHandler(0xc00030e120, {0x0, 0x4f516d}, 0xc00045a600)
	/app/cmd/converter/main.go:76 +0x4a5
net/http.HandlerFunc.ServeHTTP(0x9e4280, {0xbd3918, 0xc00035e620}, 0xc00035e620)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0xbd3918, 0xc00035e620}, 0xc00045a600)
	/usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xbd2428}, {0xbd3918, 0xc00035e620}, 0xc00045a600)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000318dc0, {0xbd5ca0, 0xc0003029f0})
	/usr/local/go/src/net/http/server.go:1930 +0xb08

**Comment by yuhao-he** [comment]
Looks like the errors are caused by eqix specifically - I didn't see errors from other collectors (yet). I'm trying to figure out why it doesn't work with eqix archives.

A few issues in the code: 
1. I only log a warning when an update can't be parsed, which led to this out-of-bound issue when reaching the end of a file.
2. We are seeing 50k+ errors because the pub/sub subscription is default to retry unack'ed messages immediately. I've set it to exponential backoff to reduce some noise.

**Comment by morrowc** [comment]
On Wed, 19 Jan 2022 00:55:40 +0000,
yuhao-he ***@***.***> wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> Looks like the errors are caused by eqix specifically - I didn't see errors from other collectors (yet). I'm trying to figure out why it doesn't work with eqix archives.
>

where did you dig out the eqix only part? (maybe I'm just seeing what is 'http logs' ?)

> A few issues in the code: 
> 1. I only log a warning when an update can't be parsed, which led to this out-of-bound issue when reaching the end of a file.
> 2. We are seeing 50k+ errors because the pub/sub subscription is default to retry unack'ed messages immediately. I've set it to exponential backoff to reduce some noise. 
> 

ah-ha! ok, cool. that sounds like a better plan :)

**Comment by yuhao-he** [comment]
> where did you dig out the eqix only part? (maybe I'm just seeing what is 'http logs' ?)

It's probably not eqix only - but I did see a ton of logs when "start conversion" messages for eqix but zero success messages (I will display error messages later). This is probably due to the immediate retries.

Btw, it looks like only around 10 collectors have been uploaded today. Is there any way to look at the progress of uploads?

**Comment by morrowc** [comment]
The uploader is seeming to have problems getting out of a single directory in the Walk() function.
I'd spent time yesterday attempting to debug it, for instance:
  https://gist.github.com/morrowc/188800b5ee4af025e037cc3f1d1de453
  
  That code will walk down like is shown in the 1st comment.
  The mass_uploader code, though, reading logs output:
    https://gist.github.com/morrowc/795ea8dfa77bb363695360282f3f9d1b

seems to never get back out of the hole it dug on the first pass through a directory.

**Comment by morrowc** [comment]
Oh, 'how to see how far its gotten'... I suppose either: "read logs" (which is hard when it's not on your workstation) or the metrics collection could be exposed better/externally? suggestions?
